### ISSUE TITLE
[BUG] path function should allow zero arguments

### ISSUE THREAD

**Issue by kylehoover** [jonnyboyC/kos-language-server#106]
**Describe the bug**
The `path` function expects 1 argument (a `path` or `string`), but the argument should be optional.

**To Reproduce**
1. Create a new `.ks` file
2. Type `path().`
3. Hover over the closing paren and the suggestion will show that the `path` function is expecting 1 argument

**Expected behavior**
As per the [documentation here](https://ksp-kos.github.io/KOS/commands/files.html#path-command) calling `path()` with no arguments creates a `Path` for the current directory. There shouldn't be a suggestion that `path` is expecting 1 argument.

**Screenshots**
![kos-path-bug](https://user-images.githubusercontent.com/16613233/64470526-ae3e4600-d101-11e9-9bcf-e2b91ed24b84.png)

**Editor**
 - OS: Windows
 - Editor: VS Code 1.38.0
 - Extension Version: 0.10.1

**Comment by jonnyboyC** [comment]
Thanks for the issue! This will be an easy fix. Please post more inconsistencies you find. This process isn't automated yet so I'm sure there are more places where something like this may have occurred

**Comment by kylehoover** [comment]
Will do! Thanks for all of the time you put into this!

**Comment by jonnyboyC** [comment]
Fixed by #107
