### ISSUE TITLE
[BUG] SHIP:CONTROL:NEUTRALIZE is detected as read-only

### ISSUE THREAD

**Issue by scimas** [jonnyboyC/kos-language-server#126]
**Describe the bug**
What the title says. In fact SHIP:CONTROL:NEUTRALIZE is not readable at all, it is *only settable*. [Link](https://ksp-kos.github.io/KOS_DOC/commands/flight/raw.html#ship-control-neutralize) to the relevant kos documentation.

**To Reproduce**
Try to set SHIP:CONTROL:NEUTRALIZE to true or false.

**Editor (please complete the following information):**
 - OS: Windows 10
 - Editor: vscode
 - Extension Version: 0.14.0

**Comment by jonnyboyC** [comment]
👍 Good catch will get that updated asap.

**Comment by jonnyboyC** [comment]
This may actually take a bit longer than I was thinking. There was somewhat of an implicit assumption on my part that a type could either be gettable, gettable and settable or neither. 

As a side note, I did find that there are actually two additional setters in `ship:control` that are not documented. specifically `ship:control:killRotation` and `ship:control:resetTrim`
