### ISSUE TITLE
[BUG] wrong error detection

### ISSUE THREAD

**Issue by astappiev** [jonnyboyC/kos-language-server#144]
**Describe the bug**
It this line the parser found an error `Expected ".".` (after `))`):
`			print (i - (1 * page)) + ") - " + Options[i].`

But if I modify the line to
`print "" + (i - (1 * page)) + ") - " + Options[i].`
the error disappears.

**Expected behavior**
Should not mark as an error.

**Editor (please complete the following information):**
 - VSCode 1.41.1
- kOS (Kerboscript) 1.1.0

**Comment by jonnyboyC** [comment]
Thanks for the report!, I'll take a look into this
