### ISSUE TITLE
[BUG] <g0 constant missing>

### ISSUE THREAD

**Issue by dwagger** [jonnyboyC/kos-language-server#151]
CONSTANT:g0 missing as suffix structure

"Unable to find suffix g0 on type constant kos-language-server (type-missing-suffix)"

https://ksp-kos.github.io/KOS/math/basic.html#global:CONSTANT:G0

**Comment by jonnyboyC** [comment]
Thanks for the the issue! This stuff is particularly hard for me to find without just endless raking through the docs. I'll get this in right away!

**Comment by jonnyboyC** [comment]
This should be fixed now in 1.1.3 in the marketplace
