### ISSUE TITLE
[BUG] kuniverse:timewarp:mode, warp and rate incorrectly identified read-only

### ISSUE THREAD

**Issue by Angalexik** [jonnyboyC/kos-language-server#152]
**Describe the bug**
`kuniverse:timewarp:mode`, `kuniverse:timewarp:warp` and `kuniverse:timewarp:rate` are identified as read-only, despite it not being the case, as seen [here](http://ksp-kos.github.io/KOS_DOC/structures/misc/timewarp.html#timewarp-structure).

**To Reproduce**
Steps to reproduce the behaviour:
1. Open editor.
2. Write any of the following lines of code:
```kerboscript
set kuniverse:timewarp:rate to 10.
set kuniverse:timewarp:mode to "RAILS".
set kuniverse:timewarp:warp to 2.
```
3. Linter complains about `type-no-setter`

**Expected behaviour**
Linter doesn't complain.

**Screenshots**
![issue](https://user-images.githubusercontent.com/58977805/82835093-4f08a780-9ec3-11ea-818f-5ebd2beb40ca.png)

**Editor:**
 - OS: Arch Linux
 - Editor: neovim with coc.nvim extension
 - Extension Version: 1.1.1

**Comment by jonnyboyC** [comment]
This should be fixed now in 1.1.3 in the marketplace
