### ISSUE TITLE
[Feature] Update npm package to 1.1.3

### ISSUE THREAD

**Issue by Angalexik** [jonnyboyC/kos-language-server#155]
**Is your feature request related to a problem? Please describe.**
The `kos-language-server` npm package is on version 1.1.1 missing features and bugfixes of the later versions.

**Describe the solution you'd like**
Update the package to the latest version

**Describe alternatives you've considered**
I've tried compiling from source but because I have no JS experience I got stuck immediately.

**Additional context**

**Comment by jonnyboyC** [comment]
@Angalexik Thanks for posting, I can probably get a updated package up on npm later today.

**Comment by jonnyboyC** [comment]
Also just out of curiosity what editor are you using?

**Comment by Angalexik** [comment]
@jonnyboyC  I'm using neovim with the coc.nvim extension for LSP support

**Comment by jonnyboyC** [comment]
Thanks for letting me know! The package has been updated to 1.1.3 https://www.npmjs.com/package/kos-language-server
