### ISSUE TITLE
[BUG] command not found

### ISSUE THREAD

**Issue by Eforen** [jonnyboyC/kos-language-server#157]
**Describe the bug**
any function is not working
* `command 'kos.startTelnet' not found`
* `command 'kos.startVscodeLog' not found`
* `command 'kos.startLspLog' not found`
* `command 'kos.searchDocs' not found`

**To Reproduce**
1. Press `Ctrl+P`
2. Type `>kOS: Connect Telnet Client`
3. Hit enter
4. See error in bottom right

**Expected behavior**
It connects to the port

**Screenshots**
![image](https://user-images.githubusercontent.com/725683/84566846-06ae0e00-ad3a-11ea-9afb-076b16c0e351.png)
![image](https://user-images.githubusercontent.com/725683/84566898-7c19de80-ad3a-11ea-9948-b36e26928481.png)

**Editor (please complete the following information):**
 - OS: Window
 - Editor: vscode
 - Extension Version: 1.1.3

**Additional context**
I may just be stupid atm... I have been working for around 24 hours and waiting for a server migration right now...

**Comment by Eforen** [comment]
Turns out I am just stupid! For anyone else who also gets this problem make sure that your VS Code is updated and if you have a pending windows update restart do that too because those cause all kinds of weird issues.

**Comment by jonnyboyC** [comment]
@Eforen glad your issue was resolved!

**Comment by Eforen** [comment]
Thank you @jonnyboyC
