### ISSUE TITLE
[BUG] Include directive not working

### ISSUE THREAD

**Issue by attrib** [jonnyboyC/kos-language-server#161]
**Describe the bug**

The `// #include "test.ks"` seems to be not working anymore.

**To Reproduce**

File `test.ks`

```
function test {
    return 0.
}
```

File `test.ks`

```
// #include "test.ks"
// runOncePath("test.ks").

test().
```

VSCode claims `Symbol test may not exist kos-language-server(symbol-may-not-exist)`

Uncommenting `runOncePath` works and test is defined.

**Expected behavior**

Should work withouth runOncePath as of #123 

**Editor (please complete the following information):**

vscode:
Version: 1.47.2 (system setup)
Commit: 17299e413d5590b14ab0340ea477cdd86ff13daf
Date: 2020-07-15T18:22:06.216Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18362

johnchabot.kos-vscode v1.1.4

**Comment by attrib** [comment]
Same with 
```
  // #include "0://test.ks"
  // runOncePath("0://test.ks").
```

As I just noticed in the changelog that this how it was announced there,

**Comment by jonnyboyC** [comment]
Thanks for the report, especially the follow up! I'm sure this will be easy to reproduce. I'll try to get this fixed up asap.

**Comment by jonnyboyC** [comment]
I still need to deploy a new version but this is now fixed on master.

**Comment by attrib** [comment]
That was quick. Thanks for all the work on the language server!

**Comment by jonnyboyC** [comment]
Feel free to post any other issues you find. I haven't been playing kOS recently but would like to keep this project maintained.
