### ISSUE TITLE
Atom support

### ISSUE THREAD

**Issue by lucaelin** [jonnyboyC/kos-language-server#6]
I'd love to see this working on atom. I've tried porting it myself but this package foo frustrates me too much :sweat_smile:  :two_hearts: :rocket:

**Comment by jonnyboyC** [comment]
I can definitely take a look at it soonish. I finalized another release for the vscode extension so I can explore how exactly I add extra editor support. More than likely I'll have to figure out how to package the server separately as an npm package. Hopefully that'll be 80% of the battle. 

I haven't used atom for much more than poking around so I may try to figure out package up a test extension for you and anyone else that's interested in trying it out.

**Comment by lucaelin** [comment]
Syntax highlighter works like charm :+1: cool to see such a quick progress :)

**Comment by jonnyboyC** [comment]
glad it working! I'll still need to figure out how to hook up the language server but I'll probably go ahead and publish the package soon.

Do the colors look correct for atom? I'm not an atom user and they seemed off to me but I don't know what the typical color pallet looks like.

**Comment by lucaelin** [comment]
I really don't know as my atom is so heavily modified, but it looks fine in my install :)

**Comment by jonnyboyC** [comment]
Current atom support has been moved to this repo. Still need to get the language server to work at some time, but it's [here](https://github.com/jonnyboyC/kos-ide)
