### ISSUE TITLE
[BUG] Region folding seems to have disabled all other folding

### ISSUE THREAD

**Issue by jefferyharrell** [jonnyboyC/kos-language-server#85]
The new region folding feature (which is awesome) appears to have disabled all other code folding. I'm not sure how to demonstrate this other than with a screenshot, so...

https://imgur.com/6hDv1Dx

Though my cursor is not visible, it's in the margin where code folding toggles show on mouseover. As you can see, I can fold the region, but I cannot fold the block ("`{...}`") within it. The same is true of `IF` blocks and other control structures as well as `DECLARE GLOBAL/LOCAL FUNCTION` blocks.

Thanks!

**Comment by jonnyboyC** [comment]
thanks for finding and reporting all of this, it really does help me quite a bit!
